### ISSUE TITLE
On increase button click, it appends the number instead of adding it

### ISSUE THREAD

**Issue by ammarmallik** [krystalcampioni/vue-number-input-spinner#12]
Reproducible Steps:
 - Change the input value manually
 - Increase number by using + button

**Comment by ammarmallik** [comment]
Verify this [Pull Request](https://github.com/krystalcampioni/vue-number-input-spinner/pull/13)

**Comment by krystalcampioni** [comment]
Thanks for the contribution @ammarmallik. I'll release you changes on the next version 👍
