### ISSUE TITLE
v-model doesn't work

### ISSUE THREAD

**Issue by YYQ8023** [krystalcampioni/vue-number-input-spinner#3]
ths.
my code just like this:
<Mynumber v-model="Num" :min="1" :max="9"/>
when i changed "Num"  by other function,the view doesn't change,but actually the value of "Num" has changed,i can get the correct value by "console.log()"。
i dont know where are you from,can you speack chinese?
unh,can you fixed as soon as  possible,ths.

when the first time i changed  "Num", the view can change correct,but after this , the problem happened,just like above

**Comment by krystalcampioni** [comment]
Hi @YYQ8023. Could you please provide me your code so I could better understand what's going on? Unfortunately, I don't speak Chinese.

**Comment by YYQ8023** [comment]
@krystalcampioni  my code maybe a little complex,here it is(a part of my code):
```
<parentComponent>
<Mynumber v-model="Num" :min="1" :max="5">
</Mynumber>
</parentComponent>
```

```
data(){
retutn{
Num:0
}
}
```
condition1：i have a watch property  : 
```watch:{
info:function(newVal,oldVal){
this.num = newVal.num
}
}
```

condition2:when i click a button ,trigger a function to change "Num",like 
```
this.Num = 2
```
then console.log(Num),i cannot get 2.

**Comment by krystalcampioni** [comment]
I'm not sure I understood your example, but it seems you are trying to force update the value from an external component. If so, that's not how the component is intended to be used. This external manipulation of the value would not go through all the checks of min value, max value, step, etc, as using the buttons or input for manipulating the value would. Feel free to fork the repo and change it to your needs though :)
