### ISSUE TITLE
More info about custom classess

### ISSUE THREAD

**Issue by jstr14** [krystalcampioni/vue-number-input-spinner#7]
Hello,

I'm using your component but I don't know how to add my custom classess to input and button.
I try to define my classes and put it on component but it doesn't work.

Can you tell me how to use this feature?

My code is like:

  <number-input-spinner
     v-if="someOptionSelected('afternoon')"
     :min="0"
     :buttonClass="inputButton"
     :integerOnly="true"/>

  .inputButton {
     border-radius: 5px;
     background-color: deepskyblue;
   }

Thanks.

**Comment by krystalcampioni** [comment]
Hello @jstr14 all good? 👋 

I think there was a bit of a misunderstanding related to how to use the custom classes. If you want that css to be applied to your button you should do the following:

On the template where you are using the component, you just pass the CSS class name that you declared on your css file, whatever the name is:

```
<NumberInputSpinner
  :inputClass="shrubles"
  :buttonClass="flamingos">
```

then, in your css file, you use the same class names to stylize the component:
```
.shrubles {
  border-radius: 5px;
  background-color: deepskyblue;
}

.flamingos {
  background: pink;
}
```

The inputClass is the CSS class name that will be applied to the text input itself, and the buttonClass is the CSS class name that wil be applied to the  + and -  buttons.

**Comment by jstr14** [comment]
Hello  @krystalcampioni  thanks for your reply.
I think there are some problems with your reply, I create the two css classes and put it on component, but component doesn't change. If css should be scoped or not.

I use your component on my own component like:
`
 <number-input-spinner
    class="is-flex"
    style="align-items: center"
    :inputClass="shrubles"
    :buttonClass="flamingos"
    v-if="someOptionSelected('afternoon')"
    :min="0"
    :integerOnly="true"/>
`
On my css I put the css classess, but It doesn't change.

Thanks

**Comment by achatrian** [comment]
Hello, in case anyone still has this problem. Since you're binding the variable, you actually have to pass a string to the attribute:
`
<NumberInputSpinner
:inputClass="'shrubles'"
:buttonClass="'flamingos'">
`
Thank you for the great component

**Comment by krystalcampioni** [comment]
@achatrian thanks for the comment, I'd mistyped that, updated my comment now removing the `:` so we don't have to use double quotes
