### ISSUE TITLE
you can use "dots" couple of times

### ISSUE THREAD

**Issue by goors** [krystalcampioni/vue-number-input-spinner#8]
Example:

you can type in 4.4.4444

**Comment by goors** [comment]
You can even type "....." without entering any number

**Comment by johndatserakis** [comment]
Hey bud - did you make sure to set `:integerOnly="true"` on your component? 

That should prevent you from being able to use dots at all.

Check out this CodeSandbox where I set that property: 

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8p39o90k1l)
